# fly.toml
app = 'subphim-server' # Thay bằng tên app của bạn
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Đảm bảo là 0 hoặc 1

# ...
[mounts]
  source = 'subphim_data'
  destination = '/data'