// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubPhim.Server.Data;

#nullable disable

namespace SubPhim.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127065323_AddSrtLimitFields419898")]
    partial class AddSrtLimitFields419898
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SubPhim.Server.Data.AioApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestsToday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AioApiKeys");
                });

            modelBuilder.Entity("SubPhim.Server.Data.AioTranslationJob", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("AioTranslationJobs");
                });

            modelBuilder.Entity("SubPhim.Server.Data.AioTranslationSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DelayBetweenChunksMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayBetweenFilesMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectSendThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableThinkingBudget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxApiRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryApiDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RpdPerKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RpmPerKey")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("ThinkingBudget")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AioTranslationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChunkSize = 3500,
                            DefaultModelName = "gemini-2.5-pro",
                            DelayBetweenChunksMs = 5000,
                            DelayBetweenFilesMs = 5000,
                            DirectSendThreshold = 8000,
                            EnableThinkingBudget = true,
                            MaxApiRetries = 3,
                            MaxOutputTokens = 8192,
                            RetryApiDelayMs = 10000,
                            RpdPerKey = 100,
                            RpmPerKey = 10,
                            Temperature = 0.7m,
                            ThinkingBudget = 8192
                        });
                });

            modelBuilder.Entity("SubPhim.Server.Data.AioTtsBatchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalSrtFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedLines")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<string>("ResultZipFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLines")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AioTtsBatchJobs");
                });

            modelBuilder.Entity("SubPhim.Server.Data.AioTtsServiceAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharactersUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedJsonKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageMonth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientEmail")
                        .IsUnique();

                    b.ToTable("AioTtsServiceAccounts");
                });

            modelBuilder.Entity("SubPhim.Server.Data.AvailableApiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PoolType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AvailableApiModels");
                });

            modelBuilder.Entity("SubPhim.Server.Data.BannedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssociatedUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hwid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownIp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BannedDevices");
                });

            modelBuilder.Entity("SubPhim.Server.Data.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hwid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SubPhim.Server.Data.GoogleTtsModelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MonthlyFreeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerMillionChars")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("SupportsPitch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsSpeakingRate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsSsml")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelType")
                        .IsUnique();

                    b.ToTable("GoogleTtsModelConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard voices - Cost-efficient general purpose TTS",
                            IsEnabled = true,
                            ModelIdentifier = "Standard",
                            ModelType = 1,
                            MonthlyFreeLimit = 4000000L,
                            PricePerMillionChars = 4.00m,
                            SupportsPitch = true,
                            SupportsSpeakingRate = true,
                            SupportsSsml = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "WaveNet voices - Premium synthetic speech with human-like quality",
                            IsEnabled = true,
                            ModelIdentifier = "Wavenet",
                            ModelType = 2,
                            MonthlyFreeLimit = 1000000L,
                            PricePerMillionChars = 16.00m,
                            SupportsPitch = true,
                            SupportsSpeakingRate = true,
                            SupportsSsml = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Neural2 voices - Premium with custom voice technology",
                            IsEnabled = true,
                            ModelIdentifier = "Neural2",
                            ModelType = 3,
                            MonthlyFreeLimit = 1000000L,
                            PricePerMillionChars = 16.00m,
                            SupportsPitch = true,
                            SupportsSpeakingRate = true,
                            SupportsSsml = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chirp 3: HD voices - Conversational agents with 30 distinct styles",
                            IsEnabled = true,
                            ModelIdentifier = "Chirp3-HD",
                            ModelType = 4,
                            MonthlyFreeLimit = 1000000L,
                            PricePerMillionChars = 30.00m,
                            SupportsPitch = false,
                            SupportsSpeakingRate = false,
                            SupportsSsml = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chirp HD voices (Legacy) - Earlier generation Chirp voices",
                            IsEnabled = false,
                            ModelIdentifier = "Chirp-HD",
                            ModelType = 5,
                            MonthlyFreeLimit = 1000000L,
                            PricePerMillionChars = 30.00m,
                            SupportsPitch = false,
                            SupportsSpeakingRate = false,
                            SupportsSsml = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Studio voices - News reading and broadcast content",
                            IsEnabled = true,
                            ModelIdentifier = "Studio",
                            ModelType = 6,
                            MonthlyFreeLimit = 1000000L,
                            PricePerMillionChars = 16.00m,
                            SupportsPitch = true,
                            SupportsSpeakingRate = true,
                            SupportsSsml = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Polyglot voices - Multilingual capability",
                            IsEnabled = true,
                            ModelIdentifier = "Polyglot",
                            ModelType = 7,
                            MonthlyFreeLimit = 1000000L,
                            PricePerMillionChars = 16.00m,
                            SupportsPitch = true,
                            SupportsSpeakingRate = true,
                            SupportsSsml = true
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "News voices - Specialized for news reading",
                            IsEnabled = true,
                            ModelIdentifier = "News",
                            ModelType = 8,
                            MonthlyFreeLimit = 1000000L,
                            PricePerMillionChars = 16.00m,
                            SupportsPitch = true,
                            SupportsSpeakingRate = true,
                            SupportsSsml = true
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Casual voices - Relaxed conversational style",
                            IsEnabled = true,
                            ModelIdentifier = "Casual",
                            ModelType = 9,
                            MonthlyFreeLimit = 1000000L,
                            PricePerMillionChars = 16.00m,
                            SupportsPitch = true,
                            SupportsSpeakingRate = true,
                            SupportsSsml = true
                        });
                });

            modelBuilder.Entity("SubPhim.Server.Data.LocalApiSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayBetweenBatchesMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableThinkingBudget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rpm")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("ThinkingBudget")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LocalApiSettings");
                });

            modelBuilder.Entity("SubPhim.Server.Data.ManagedApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRequestCountResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoolType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestsToday")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTokensUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ManagedApiKeys");
                });

            modelBuilder.Entity("SubPhim.Server.Data.OriginalSrtLineDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("OriginalSrtLines");
                });

            modelBuilder.Entity("SubPhim.Server.Data.SaOcrServiceAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveFolderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedJsonKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientEmail")
                        .IsUnique();

                    b.ToTable("SaOcrServiceAccounts");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TierDefaultSetting", b =>
                {
                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AioCharacterLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AioRequestsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedApiAccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedApis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyLocalSrtLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailySrtLineLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyTranslationRequests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyVideoCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrantedFeatures")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TtsCharacterLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Tier");

                    b.ToTable("TierDefaultSettings");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TranslatedSrtLineDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LineIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("TranslatedSrtLines");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TranslationGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemInstruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TranslationGenres");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TranslationJobDb", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLinesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasRefunded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemInstruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.ToTable("TranslationJobs");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TranslationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineCountApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineCountRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TranslationLogs");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TtsApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharactersUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestsToday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TtsApiKeys");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TtsModelSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRequestsPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRequestsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TtsModelSettings");
                });

            modelBuilder.Entity("SubPhim.Server.Data.UpdateInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UpdateInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DownloadUrl = "https://example.com/download/latest",
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LatestVersion = "1.0.0",
                            ReleaseNotes = "Phiên bản đầu tiên."
                        });
                });

            modelBuilder.Entity("SubPhim.Server.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AioCharacterLimitOverride")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AioCharactersUsedToday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AioRpmOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedApiAccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyLocalSrtLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyRequestCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyRequestLimitOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailySrtLineLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyVideoLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("GrantedFeatures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAioResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDeviceResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLocalSrtResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRequestResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSrtLineResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastTtsResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastVideoResetUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalSrtLinesUsedToday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDevices")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SrtLinesUsedToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubscriptionExpiry")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TtsCharacterLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TtsCharactersUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoDurationLimitMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideosProcessedToday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SubPhim.Server.Data.AioTranslationJob", b =>
                {
                    b.HasOne("SubPhim.Server.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SubPhim.Server.Data.AioTtsBatchJob", b =>
                {
                    b.HasOne("SubPhim.Server.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SubPhim.Server.Data.Device", b =>
                {
                    b.HasOne("SubPhim.Server.Data.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SubPhim.Server.Data.OriginalSrtLineDb", b =>
                {
                    b.HasOne("SubPhim.Server.Data.TranslationJobDb", "Job")
                        .WithMany("OriginalLines")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TranslatedSrtLineDb", b =>
                {
                    b.HasOne("SubPhim.Server.Data.TranslationJobDb", "Job")
                        .WithMany("TranslatedLines")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TranslationLog", b =>
                {
                    b.HasOne("SubPhim.Server.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SubPhim.Server.Data.TranslationJobDb", b =>
                {
                    b.Navigation("OriginalLines");

                    b.Navigation("TranslatedLines");
                });

            modelBuilder.Entity("SubPhim.Server.Data.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
